version: "3.8"

services:
  mantisbt:
    image: xlrl/mantisbt:2.25.4
    container_name: mantisbt
    ports:
      - "8989:80"
    links:
      - mysql
    restart: always
    networks:
      - test-network

  mysql:
    image: mariadb:latest
    container_name: mantisbt-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=e2eW3Bt3s71nGB3nchM4rK
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    restart: always
    networks:
      - test-network

  maven-java21:
    image: maven:3.9-eclipse-temurin-21
    container_name: mantisbt-2.25.4-maven
    working_dir: /app
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    networks:
      - test-network
    depends_on:
      - browser
      - mantisbt

  browser:
    image: selenium/standalone-chrome:latest
    container_name: browser
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_START_XVFB=true
      - SE_START_VNC=true
      - SE_START_NO_VNC=true
    networks:
      - test-network

  chrome-video:
    image: selenium/video:latest
    container_name: chrome-video
    depends_on:
      - browser
    volumes:
      - ./videos:/videos
    environment:
      - DISPLAY_CONTAINER_NAME=browser
      - SE_VIDEO_FILE_NAME=auto
      - SE_VIDEO_FILE_NAME_SUFFIX=false
      - SE_VIDEO_RECORD_STANDALONE=true
      - SE_NODE_GRID_URL=http://browser:4444
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  maven-repo: